# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('REPORTED', 'REPORTED'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='REPORTED', max_length=11),
        ),
    ]
