# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
