# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-15 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0004_auto_20191215_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='voters',
        ),
        migrations.AddField(
            model_name='vote',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
    ]
