# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-15 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0005_auto_20191215_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voters',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('issue', 'voter')]),
        ),
    ]
