# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-27 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20191226_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
