# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_auto_20191227_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, max_length=6),
        ),
    ]
