# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_auto_20191227_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('a', 'Low'), ('b', 'Medium'), ('c', 'High')], default='a', max_length=6),
        ),
    ]
