# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0023_auto_20191227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
