# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0024_auto_20200112_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
