# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-19 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0028_auto_20200119_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
