# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='card_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
