# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-30 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='featurecommenter', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='features.Feature')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
                ('voter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='featurevoter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('feature', 'voter')]),
        ),
    ]
