# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-19 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_auto_20191230_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
