# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-08 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0003_feature_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_reported_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
