# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-07 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_commenter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('category', models.CharField(choices=[('ISSUE', 'ISSUE'), ('FEATURE', 'FEATURE')], default='ISSUE', max_length=10)),
                ('description', models.TextField(max_length=300)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=6)),
                ('state', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('REPORTED', 'REPORTED'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='REPORTED', max_length=11)),
                ('votes', models.IntegerField(default=0)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reported_by', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-votes',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
                ('voter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_voter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('ticket', 'voter')]),
        ),
    ]
