# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.CharField(default='', max_length=600),
        ),
    ]
